sudo: false
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
branches:
  only:
    - master
    - /^release\/.*$/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
before_install:
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager --update
install:
  - echo y | sdkmanager "ndk-bundle" >/dev/null
  - echo y | sdkmanager "cmake;3.10.2.4988404" >/dev/null
before_script:
  - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
android:
  components:
    - platform-tools
    - build-tools-29.0.2
    - android-29
os: linux
dist: trusty
language: android
matrix:
  include:
    - jdk: openjdk8
      after_success:
        - bash <(curl -s https://codecov.io/bash)
notifications:
  webhooks:
    urls:
      - https://zeus.ci/hooks/d904a9f8-490e-11ea-90b6-2a42b8bf05e4/public/provider/travis/webhook
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
after_success:
  - ./scripts/zeus.sh
