name: Workflow Sample Install macOS
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      # Zulu Community distribution of OpenJDK
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Generate Gradle checksums
        run: |
          find buildSrc -name "*.kt" -type f | sort | xargs shasum  > gradle-checksums.txt
          cat gradle-checksums.txt
      - uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('gradle-checksums.txt') }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ hashFiles('gradle-checksums.txt') }}-

      - name: run tests
      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          ndk: 21.0.6113669
          cmake: 3.10.2.4988404
          script: make runConnectedTests

      # We stop gradle at the end to make sure the cache folders
      # don't contain any lock files and are free to be cached.
      - name: Make stop
        run: make stop
