name: Workflow Sample Install macOS
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

env:
  CMAKE_VERSION: "3.10.2.4988404"

jobs:
  build:
    runs-on: macOS-10.15

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      # Zulu Community distribution of OpenJDK
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: set up sdkmanager and emulators
        uses: malinskiy/action-android/install-sdk@release/0.0.7
      - run: echo $ANDROID_HOME
      - run: sdkmanager platform-tools
      - run: adb devices
      - run: sdkmanager --install "cmake;${CMAKE_VERSION}"

      - uses: malinskiy/action-android/emulator-run-cmd@release/0.0.7
        with:
          cmd: ./gradlew installDebug
          api: 25
          tag: default
          abi: x86

      - name: Save logcat output
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: logcat
          path: artifacts/logcat.log
