name: Android CI Windows
on: [push, pull_request]

env:
  # CMAKE_VERSION: "3.10.2.4988404"
  NDK_VERSION: "21.1.6352462"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      # Zulu Community distribution of OpenJDK
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set path
        run: set PATH=%PATH%;"%ANDROID_HOME%\tools\bin"
        shell: cmd

      - name: Install NDK 21.1
        run: sdkmanager "ndk;%NDK_VERSION%"

      - name: Cache Gradle Caches
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches/
          key: cache-gradle-cache

      - name: Cache Gradle Wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper/
          key: cache-gradle-wrapper

      # uses eskatos/gradle-command-action, so we don't care for ./gradlew or gradlew.bat

      - name: Clean and Build
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: clean build

      # We stop gradle at the end to make sure the cache folders
      # don't contain any lock files and are free to be cached.
      - name: Stop Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: --stop
